name: Build ICS

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-ics:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate weekend schedule
        run: python scrape_weekend_time.py weekend_schedule.ics

      - name: Commit calendar update
        run: |
          if [[ -n $(git status --porcelain weekend_schedule.ics) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add weekend_schedule.ics
            git commit -m "chore: update weekend schedule"
            git push
          else
            echo "No changes to commit"
          fi

      - name: Upload ICS artifact
        uses: actions/upload-artifact@v4
        with:
          name: weekend-schedule
          path: weekend_schedule.ics
